CREATE TABLE IF NOT EXISTS hephaestus.items
(
    id                    INTEGER PRIMARY KEY,
    name                  VARCHAR(255) NOT NULL,
    last_updated          VARCHAR(255) NOT NULL,
    incomplete            boolean      NOT NULL,
    members               boolean      NOT NULL,
    tradeable             boolean      NOT NULL,
    tradeable_on_ge       boolean      NOT NULL,
    stackable             boolean      NOT NULL,
    stacked               INTEGER,
    noted                 boolean      NOT NULL,
    noteable              boolean      NOT NULL,
    linked_id_item        INTEGER,
    linked_id_noted       INTEGER,
    linked_id_placeholder INTEGER,
    placeholder           boolean      NOT NULL,
    equipable             boolean      NOT NULL,
    equipable_by_player   boolean      NOT NULL,
    equipable_weapon      boolean      NOT NULL,
    cost                  INTEGER      NOT NULL,
    lowalch               INTEGER,
    highalch              INTEGER,
    weight                FLOAT,
    buy_limit             INTEGER,
    quest_item            boolean      NOT NULL,
    release_date          VARCHAR(255),
    duplicate             boolean      NOT NULL,
    examine               VARCHAR(2000),
    icon                  VARCHAR(2580) NOT NULL,
    wiki_name             VARCHAR(255),
    wiki_url              VARCHAR(255),
    equipment             json,
    weapon                json
);